version: "3.8"
services:
  web:
    image: nginx:latest
    volumes:
    - ".:/app"
    - "./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
    ports:
    - "8000:80"
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ".:/app"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: duikclubdolfijn_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
